### ISSUE TITLE
"Show Correct Response" does not reorder choices to order of correct response

### ISSUE THREAD

**Issue by benburton** [PieElements/corespring-placement-ordering#6]
**Steps to Reproduce:**
1. Install [`pie-cli`](https://github.com/PieLabs/pie-cli)
2. Clone [`pie-docs`](https://github.com/pielabs/pie-docs) (at present on the [`feature/quickstart-fix`](https://github.com/PieLabs/pie-docs/tree/feature/quickstart-fix) branch)
3. `cd` into `pie-docs/using/demo-item`
4. Run `pie pack`
5. Run `pie serve`
6. Navigate to http://localhost:4000
7. In the `corespring-placement-ordering` question prompted by "Arrange these countries in the order that they joined the EU" enter an incorrect order (e.g., "Italy", "Sweden", "Spain", "Denmark").
8. From the "view" drop down in the upper-left corner of the page, change from "view" to "evaluate".
9. Observe that some items are highlighted green, others orange, and there is a "Show correct answer" toggle displayed.
10. Click the "Show correct answer toggle"

**Expected Behavior:** The items are rearranged in the correct order (i.e., "Italy", "Denmark", "Spain", "Sweden"), all with a green border.

**Actual Behavior:** The items are not rearranged; they retain their order. The border on all the choices do turn green, however.

**Comment by amiklosi** [comment]
I'm not able to reproduce this on develop. Will check with Ben.

**Comment by benburton** [comment]
I was also unable to reproduce this issue. Closing.
